### ISSUE TITLE
[Feature Request] Color settings per icon

### ISSUE THREAD

**Issue by Aquaterion** [watery-desert/sliding_clipped_nav_bar#1]
Optionally, one could provide inactive and active colors to the BarItem. If they exist it would take priority over the Bar's colors.

First use case that comes to mind is apps that have free service and a paid service. Usually there would be a button dedicated to the paid service, and apps normally make it stand out more by giving it a brighter color.

Other use cases include just wanting a colorful navigation bar, or maybe gradient like coloring, where each icon is slightly darker/light than the other.

**Comment by watery-desert** [comment]
@Aquaterion I added a named constructor `SlidingClippedNavBar.colorful()` you can new set individual item icon color.
