### ISSUE TITLE
Make a posibility to have BarItem without text

### ISSUE THREAD

**Issue by Marek00Malik** [watery-desert/sliding_clipped_nav_bar#5]
It would be great if we could have the possibility to have a BarItem that is not switching between Text and Icon. 
Can we do it somehow?

**Comment by watery-desert** [comment]
I did not understand, can you provide some image to explain?

**Comment by Marek00Malik** [comment]
Sure no problem. 
Basically, I would like to lose this `title` required property from the `BarItem`

So I would only have the dot appear on the icon when I click on the BarItem.
<img width="48" alt="Zrzut ekranu 2022-01-4 o 12 54 40" src="https://user-images.githubusercontent.com/6674859/148055687-d6d7c047-eb8c-4699-b36e-2861160b8d2e.png"> and not   <img width="57" alt="Zrzut ekranu 2022-01-4 o 12 54 15" src="https://user-images.githubusercontent.com/6674859/148055536-da6d4817-784e-4bb8-90e5-4b231cffb8b7.png">

**Comment by watery-desert** [comment]
Hmm, that's just another bottom navigation bar design. If you see the original [design here](https://dribbble.com/shots/5605168-Toolbar-icons-animation) I did exactly the same the title is essential. I would suggest you to fork the package and replace the Text with Icon, you may need to adjust the offset a bit.

**Comment by watery-desert** [comment]
closing because of no further response.
