### ISSUE TITLE
customize COlor for text

### ISSUE THREAD

**Issue by rulefahd** [watery-desert/sliding_clipped_nav_bar#9]
i noticed in your last update , the button text is no longer takes the color of the active color , instead it takes the color of body color , how can i change the color of it without changing the body color of the whole app

**Comment by watery-desert** [comment]
I did not understand this issue.

**Comment by watery-desert** [comment]
I pushed an update. Try to add this to your project and see. Make sure you have to add from git I didn't update on pub.

```dart
 dependencies:
  sliding_clipped_nav_bar:
    git:
      url: https://github.com/watery-desert/sliding_clipped_nav_bar  
```

**Comment by watery-desert** [comment]
closing, since no reply.

**Comment by rulefahd** [comment]
Sorry for late reply ,

yes this fixes it , Thank you
